### ISSUE TITLE
🐛 Coverage is empty (0%) on CI

### ISSUE THREAD

**Issue by aivascu** [aivascu/AutoFixture.Community.AutoMapper#10]
### Describe the Bug

Coverage is generated as 0% on CI. [example](https://github.com/aivascu/AutoFixture.Community.AutoMapper/runs/4577042551?check_suite_focus=true#step:4:82)

### Scenario

N/A

### Expected Behavior

Appropriate coverage is shown

### Tasks

- [x] Installed the last version
- [x] Updated all AutoFixture and related libraries
- [x] Confirmed in support forums if behavior is expected

### More Information

N/A

### Screenshots

N/A
