### ISSUE TITLE
🐛 Update actions/checkout@v1 to v2

### ISSUE THREAD

**Issue by aivascu** [aivascu/AutoFixture.Community.AutoMapper#8]
### Describe the Bug

Update actions/checkout@v1, which contains vulnerabilities, to v2

### Scenario

N/A

### Expected Behavior

N/A

### Tasks

- [x] Installed the last version
- [x] Updated all AutoFixture and related libraries
- [x] Confirmed in support forums if behavior is expected

### More Information

N/A

### Screenshots

N/A

Thanks!
